version: "3.9"
services:
  webapp:
    image: docker.io/norman1910/alpha-code-webapp:latest
    container_name: alpha-code-webapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped