name: Build, Push Docker Image and Deploy Webapp with Docker

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: norman1910/alpha-code-webapp:latest
          cache-from: type=registry,ref=norman1910/alpha-code-webapp:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Ensure Traefik network exists
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << EOF
            docker network inspect traefik-network || docker network create traefik-network
          EOF

      - name: Deploy webapp via Docker Compose over SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << EOF
            set -e
            cd /home/norman/SEP
            docker compose pull alpha-webapp
            docker compose up -d alpha-webapp
          EOF
